In [1]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
import numpy as np

In [2]:
import pandas as pd

df = pd.read_csv("the-circor-digiscope-phonocardiogram-dataset-1.0.3/training_data.csv")
df

Patient ID Recording locations:    Age     Sex  Height  Weight  \
0          2530          AV+PV+TV+MV  Child  Female    98.0    15.9   
1          9979          AV+PV+TV+MV  Child  Female   103.0    13.1   
2          9983          AV+PV+TV+MV  Child    Male   115.0    19.1   
3         13918          AV+PV+TV+MV  Child    Male    98.0    15.9   
4         14241          AV+PV+TV+MV  Child    Male    87.0    11.2   
..          ...                  ...    ...     ...     ...     ...   
937       85340          AV+PV+TV+MV  Child    Male   105.0    16.6   
938       85341          AV+PV+TV+MV  Child    Male    92.0    15.2   
939       85343          AV+PV+TV+MV  Child  Female    97.0    13.5   
940       85345                AV+PV  Child  Female   132.0    38.1   
941       85349             AV+PV+TV    NaN  Female     NaN     NaN   

     Pregnancy status   Murmur Murmur locations Most audible location  ...  \
0               False   Absent              NaN                   NaN  ...   
1               False  Present      AV+MV+PV+TV                    TV  ...   
2               False  Unknown              NaN                   NaN  ...   
3               False  Present               TV                    TV  ...   
4               False  Present      AV+MV+PV+TV                    PV  ...   
..                ...      ...              ...                   ...  ...   
937             False   Absent              NaN                   NaN  ...   
938             False   Absent              NaN                   NaN  ...   
939             False  Present            MV+TV                    TV  ...   
940             False   Absent              NaN                   NaN  ...   
941              True   Absent              NaN                   NaN  ...   

    Systolic murmur pitch Systolic murmur quality Diastolic murmur timing  \
0                     NaN                     NaN                     NaN   
1                    High                   Harsh                     NaN   
2                     NaN                     NaN                     NaN   
3                     Low                 Blowing                     NaN   
4                     Low                   Harsh                     NaN   
..                    ...                     ...                     ...   
937                   NaN                     NaN                     NaN   
938                   NaN                     NaN                     NaN   
939                   Low                 Blowing                     NaN   
940                   NaN                     NaN                     NaN   
941                   NaN                     NaN                     NaN   

    Diastolic murmur shape Diastolic murmur grading Diastolic murmur pitch  \
0                      NaN                      NaN                    NaN   
1                      NaN                      NaN                    NaN   
2                      NaN                      NaN                    NaN   
3                      NaN                      NaN                    NaN   
4                      NaN                      NaN                    NaN   
..                     ...                      ...                    ...   
937                    NaN                      NaN                    NaN   
938                    NaN                      NaN                    NaN   
939                    NaN                      NaN                    NaN   
940                    NaN                      NaN                    NaN   
941                    NaN                      NaN                    NaN   

    Diastolic murmur quality   Outcome Campaign Additional ID  
0                        NaN  Abnormal   CC2015           NaN  
1                        NaN  Abnormal   CC2015           NaN  
2                        NaN  Abnormal   CC2015           NaN  
3                        NaN  Abnormal   CC2015           NaN  
4                        NaN  Abn

In [3]:
patient_id = list(df["Patient ID"])
recording_loc = list(df["Recording locations:"])
murmur = list(df["Murmur"])
murmur_loc = list(df["Murmur locations"])

In [4]:
recording_loc = [x.split("+") for x in recording_loc]

for i in range(len(murmur_loc)):
    if murmur_loc[i] is np.nan:
        murmur_loc[i] = []
    else:
        murmur_loc[i] = murmur_loc[i].split("+")

In [5]:
X = []
y = []

for i in range(len(patient_id)):
    if murmur[i] == "Absent":
        for recloc in recording_loc[i]:
            X.append(np.loadtxt("SSE/" + str(patient_id[i]) + "_" + recloc + "_features.csv", delimiter=',')[:200])
            y.append(0)
    elif murmur[i] == "Present":
        for recloc in recording_loc[i]:
            if recloc in murmur_loc[i]:
                X.append(np.loadtxt("SSE/" + str(patient_id[i]) + "_" + recloc + "_features.csv", delimiter=',')[:200])
                y.append(1)
            else:
                X.append(np.loadtxt("SSE/" + str(patient_id[i]) + "_" + recloc + "_features.csv", delimiter=',')[:200])
                y.append(0)
    print("Completed patient #", str(i+1))

Completed patient # 1
Completed patient # 2
Completed patient # 3
Completed patient # 4
Completed patient # 5
Completed patient # 6
Completed patient # 7
Completed patient # 8
Completed patient # 9
Completed patient # 10
Completed patient # 11
Completed patient # 12
Completed patient # 13
Completed patient # 14
Completed patient # 15
Completed patient # 16
Completed patient # 17
Completed patient # 18
Completed patient # 19
Completed patient # 20
Completed patient # 21
Completed patient # 22
Completed patient # 23
Completed patient # 24
Completed patient # 25
Completed patient # 26
Completed patient # 27
Completed patient # 28
Completed patient # 29
Completed patient # 30
Completed patient # 31
Completed patient # 32
Completed patient # 33
Completed patient # 34
Completed patient # 35
Completed patient # 36
Completed patient # 37
Completed patient # 38
Completed patient # 39
Completed patient # 40
Completed patient # 41
Completed patient # 42
Completed patient # 43
Completed patient # 

Completed patient # 349
Completed patient # 350
Completed patient # 351
Completed patient # 352
Completed patient # 353
Completed patient # 354
Completed patient # 355
Completed patient # 356
Completed patient # 357
Completed patient # 358
Completed patient # 359
Completed patient # 360
Completed patient # 361
Completed patient # 362
Completed patient # 363
Completed patient # 364
Completed patient # 365
Completed patient # 366
Completed patient # 367
Completed patient # 368
Completed patient # 369
Completed patient # 370
Completed patient # 371
Completed patient # 372
Completed patient # 373
Completed patient # 374
Completed patient # 375
Completed patient # 376
Completed patient # 377
Completed patient # 378
Completed patient # 379
Completed patient # 380
Completed patient # 381
Completed patient # 382
Completed patient # 383
Completed patient # 384
Completed patient # 385
Completed patient # 386
Completed patient # 387
Completed patient # 388
Completed patient # 389
Completed patien

Completed patient # 691
Completed patient # 692
Completed patient # 693
Completed patient # 694
Completed patient # 695
Completed patient # 696
Completed patient # 697
Completed patient # 698
Completed patient # 699
Completed patient # 700
Completed patient # 701
Completed patient # 702
Completed patient # 703
Completed patient # 704
Completed patient # 705
Completed patient # 706
Completed patient # 707
Completed patient # 708
Completed patient # 709
Completed patient # 710
Completed patient # 711
Completed patient # 712
Completed patient # 713
Completed patient # 714
Completed patient # 715
Completed patient # 716
Completed patient # 717
Completed patient # 718
Completed patient # 719
Completed patient # 720
Completed patient # 721
Completed patient # 722
Completed patient # 723
Completed patient # 724
Completed patient # 725
Completed patient # 726
Completed patient # 727
Completed patient # 728
Completed patient # 729
Completed patient # 730
Completed patient # 731
Completed patien

In [6]:
time_steps = 200
feature_length = 18
batch_size = 1

In [7]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.33)

In [8]:
print(len(X_train), len(y_train))
print(len(X_test), len(y_test))

2014 2014
993 993


In [9]:
model = Sequential()
model.add(LSTM(32))
model.add(Dense(1, activation="sigmoid"))

In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [11]:
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [12]:
model.fit(X_train, y_train, epochs=10, batch_size=batch_size)

Epoch 1/10


2014/2014 [==============================] - 26s 12ms/step - loss: 0.4838 - accuracy: 0.8049
Epoch 2/10
2014/2014 [==============================] - 26s 13ms/step - loss: 0.4511 - accuracy: 0.8312
Epoch 3/10
2014/2014 [==============================] - 26s 13ms/step - loss: 0.4464 - accuracy: 0.8327
Epoch 4/10
2014/2014 [==============================] - 27s 13ms/step - loss: 0.4434 - accuracy: 0.8322
Epoch 5/10
2014/2014 [==============================] - 27s 13ms/step - loss: 0.4407 - accuracy: 0.8322
Epoch 6/10
2014/2014 [==============================] - 28s 14ms/step - loss: 0.4387 - accuracy: 0.8322
Epoch 7/10
2014/2014 [==============================] - 29s 14ms/step - loss: 0.4378 - accuracy: 0.8322
Epoch 8/10
2014/2014 [==============================] - 27s 13ms/step - loss: 0.4366 - accuracy: 0.8317
Epoch 9/10
2014/2014 [==============================] - 26s 13ms/step - loss: 0.4357 - accuracy: 0.8317
Epoch 10/10
2014/2014 [==============================] - 27s 1

In [13]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [14]:
score = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=0)
print('Test loss:', score[0])
print('Accuracy:', score[1])

Test loss: 0.43870189785957336
Accuracy: 0.8388720750808716


In [15]:
X = np.array(X)
y = np.array(y)
y

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
score_full = model.evaluate(X, y, batch_size=batch_size, verbose=0)
print('Test loss:', score_full[0])
print('Accuracy:', score_full[1])

Test loss: 0.43661704659461975
Accuracy: 0.83438640832901


In [17]:
model.predict(X_test)

32/32 [==============================] - 1s 7ms/step


array([[0.07919616],
       [0.12649933],
       [0.08014005],
       [0.11097859],
       [0.3079281 ],
       [0.20879744],
       [0.09627298],
       [0.13006626],
       [0.13075548],
       [0.18761162],
       [0.26710942],
       [0.33038253],
       [0.13133521],
       [0.06837372],
       [0.11063296],
       [0.13269107],
       [0.10330813],
       [0.1327487 ],
       [0.11087814],
       [0.12673232],
       [0.15387505],
       [0.22104639],
       [0.10313131],
       [0.11712052],
       [0.08152467],
       [0.08154816],
       [0.22480851],
       [0.17663963],
       [0.19929904],
       [0.12328596],
       [0.13077635],
       [0.23511575],
       [0.09967626],
       [0.11977215],
       [0.12684456],
       [0.12603289],
       [0.12009414],
       [0.28150338],
       [0.10108312],
       [0.13132516],
       [0.10571825],
       [0.17149939],
       [0.08166409],
       [0.17766027],
       [0.20045212],
       [0.10326187],
       [0.10108691],
       [0.190

In [18]:
final_final_predicts = model.predict(X_test)
final_final_predicts.shape

32/32 [==============================] - 0s 8ms/step


(993, 1)

In [26]:
for i in range(993):
    if final_final_predicts[i][0] >= 0.4:
        print("Test number", str(i+1), "/993:", final_final_predicts[i][0])

Test number 168 /993: 0.43606216
Test number 494 /993: 0.47228816
Test number 777 /993: 0.51326936
Test number 989 /993: 0.44694364
