In [1]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

In [2]:
import pandas as pd

df = pd.read_csv("the-circor-digiscope-phonocardiogram-dataset-1.0.3/training_data.csv")
df

Patient ID Recording locations:    Age     Sex  Height  Weight  \
0          2530          AV+PV+TV+MV  Child  Female    98.0    15.9   
1          9979          AV+PV+TV+MV  Child  Female   103.0    13.1   
2          9983          AV+PV+TV+MV  Child    Male   115.0    19.1   
3         13918          AV+PV+TV+MV  Child    Male    98.0    15.9   
4         14241          AV+PV+TV+MV  Child    Male    87.0    11.2   
..          ...                  ...    ...     ...     ...     ...   
937       85340          AV+PV+TV+MV  Child    Male   105.0    16.6   
938       85341          AV+PV+TV+MV  Child    Male    92.0    15.2   
939       85343          AV+PV+TV+MV  Child  Female    97.0    13.5   
940       85345                AV+PV  Child  Female   132.0    38.1   
941       85349             AV+PV+TV    NaN  Female     NaN     NaN   

     Pregnancy status   Murmur Murmur locations Most audible location  ...  \
0               False   Absent              NaN                   NaN  ...   
1               False  Present      AV+MV+PV+TV                    TV  ...   
2               False  Unknown              NaN                   NaN  ...   
3               False  Present               TV                    TV  ...   
4               False  Present      AV+MV+PV+TV                    PV  ...   
..                ...      ...              ...                   ...  ...   
937             False   Absent              NaN                   NaN  ...   
938             False   Absent              NaN                   NaN  ...   
939             False  Present            MV+TV                    TV  ...   
940             False   Absent              NaN                   NaN  ...   
941              True   Absent              NaN                   NaN  ...   

    Systolic murmur pitch Systolic murmur quality Diastolic murmur timing  \
0                     NaN                     NaN                     NaN   
1                    High                   Harsh                     NaN   
2                     NaN                     NaN                     NaN   
3                     Low                 Blowing                     NaN   
4                     Low                   Harsh                     NaN   
..                    ...                     ...                     ...   
937                   NaN                     NaN                     NaN   
938                   NaN                     NaN                     NaN   
939                   Low                 Blowing                     NaN   
940                   NaN                     NaN                     NaN   
941                   NaN                     NaN                     NaN   

    Diastolic murmur shape Diastolic murmur grading Diastolic murmur pitch  \
0                      NaN                      NaN                    NaN   
1                      NaN                      NaN                    NaN   
2                      NaN                      NaN                    NaN   
3                      NaN                      NaN                    NaN   
4                      NaN                      NaN                    NaN   
..                     ...                      ...                    ...   
937                    NaN                      NaN                    NaN   
938                    NaN                      NaN                    NaN   
939                    NaN                      NaN                    NaN   
940                    NaN                      NaN                    NaN   
941                    NaN                      NaN                    NaN   

    Diastolic murmur quality   Outcome Campaign Additional ID  
0                        NaN  Abnormal   CC2015           NaN  
1                        NaN  Abnormal   CC2015           NaN  
2                        NaN  Abnormal   CC2015           NaN  
3                        NaN  Abnormal   CC2015           NaN  
4                        NaN  Abn

In [3]:
patient_id = list(df["Patient ID"])
recording_loc = list(df["Recording locations:"])
murmur = list(df["Murmur"])
murmur_loc = list(df["Murmur locations"])

In [4]:
recording_loc = [x.split("+") for x in recording_loc]

for i in range(len(murmur_loc)):
    if murmur_loc[i] is np.nan:
        murmur_loc[i] = []
    else:
        murmur_loc[i] = murmur_loc[i].split("+")

In [5]:
a = np.loadtxt("SSE/2530_AV_features.csv", delimiter=',')
a = a[:200]
a = np.transpose(a)
print(len(a))
print(len(a[0]))
a

18
200


array([[ 92923.26476225, 105762.37397806,  18524.49465621, ...,
          4554.68952884,   2479.35633719,   1310.75655817],
       [ 37870.12939134,  64230.67469676,  67435.92558387, ...,
         11104.82276538,   7939.49032358,   3723.6484673 ],
       [ 20320.78389592,  25448.63861722,  46146.15899984, ...,
         17949.95400352,  27262.41824216,  22755.22775115],
       ...,
       [334306.99274639,  49079.92967205,  39657.07591147, ...,
         81955.99898218, 109916.2858877 ,  73406.88957754],
       [297942.86418516,  20543.63609765,  29343.11311349, ...,
         59927.8216453 ,  55893.63796523,  35704.1626206 ],
       [ 99263.00216464,   7812.46077105,   9801.38425112, ...,
         12464.27150571,   5658.77226514,   8002.61417131]])

In [6]:
X = []
y = []

for i in range(len(patient_id)):
    if murmur[i] == "Absent":
        for recloc in recording_loc[i]:
            X.append(np.loadtxt("SSE/" + str(patient_id[i]) + "_" + recloc + "_features.csv", delimiter=',')[:200])
            y.append(0)
    elif murmur[i] == "Present":
        for recloc in recording_loc[i]:
            if recloc in murmur_loc[i]:
                X.append(np.loadtxt("SSE/" + str(patient_id[i]) + "_" + recloc + "_features.csv", delimiter=',')[:200])
                y.append(1)
            else:
                X.append(np.loadtxt("SSE/" + str(patient_id[i]) + "_" + recloc + "_features.csv", delimiter=',')[:200])
                y.append(0)
    print("Completed patient #", str(i+1))

Completed patient # 1
Completed patient # 2
Completed patient # 3
Completed patient # 4
Completed patient # 5
Completed patient # 6
Completed patient # 7
Completed patient # 8
Completed patient # 9
Completed patient # 10
Completed patient # 11
Completed patient # 12
Completed patient # 13
Completed patient # 14
Completed patient # 15
Completed patient # 16
Completed patient # 17
Completed patient # 18
Completed patient # 19
Completed patient # 20
Completed patient # 21
Completed patient # 22
Completed patient # 23
Completed patient # 24
Completed patient # 25
Completed patient # 26
Completed patient # 27
Completed patient # 28
Completed patient # 29
Completed patient # 30
Completed patient # 31
Completed patient # 32
Completed patient # 33
Completed patient # 34
Completed patient # 35
Completed patient # 36
Completed patient # 37
Completed patient # 38
Completed patient # 39
Completed patient # 40
Completed patient # 41
Completed patient # 42
Completed patient # 43
Completed patient # 

Completed patient # 347
Completed patient # 348
Completed patient # 349
Completed patient # 350
Completed patient # 351
Completed patient # 352
Completed patient # 353
Completed patient # 354
Completed patient # 355
Completed patient # 356
Completed patient # 357
Completed patient # 358
Completed patient # 359
Completed patient # 360
Completed patient # 361
Completed patient # 362
Completed patient # 363
Completed patient # 364
Completed patient # 365
Completed patient # 366
Completed patient # 367
Completed patient # 368
Completed patient # 369
Completed patient # 370
Completed patient # 371
Completed patient # 372
Completed patient # 373
Completed patient # 374
Completed patient # 375
Completed patient # 376
Completed patient # 377
Completed patient # 378
Completed patient # 379
Completed patient # 380
Completed patient # 381
Completed patient # 382
Completed patient # 383
Completed patient # 384
Completed patient # 385
Completed patient # 386
Completed patient # 387
Completed patien

Completed patient # 689
Completed patient # 690
Completed patient # 691
Completed patient # 692
Completed patient # 693
Completed patient # 694
Completed patient # 695
Completed patient # 696
Completed patient # 697
Completed patient # 698
Completed patient # 699
Completed patient # 700
Completed patient # 701
Completed patient # 702
Completed patient # 703
Completed patient # 704
Completed patient # 705
Completed patient # 706
Completed patient # 707
Completed patient # 708
Completed patient # 709
Completed patient # 710
Completed patient # 711
Completed patient # 712
Completed patient # 713
Completed patient # 714
Completed patient # 715
Completed patient # 716
Completed patient # 717
Completed patient # 718
Completed patient # 719
Completed patient # 720
Completed patient # 721
Completed patient # 722
Completed patient # 723
Completed patient # 724
Completed patient # 725
Completed patient # 726
Completed patient # 727
Completed patient # 728
Completed patient # 729
Completed patien

In [7]:
print(len(X))
print(len(X[0]))
print(len(X[0][0]))
X[0]

3007
200
18


array([[ 92923.26476225,  37870.12939134,  20320.78389592, ...,
        334306.99274639, 297942.86418516,  99263.00216464],
       [105762.37397806,  64230.67469676,  25448.63861722, ...,
         49079.92967205,  20543.63609765,   7812.46077105],
       [ 18524.49465621,  67435.92558387,  46146.15899984, ...,
         39657.07591147,  29343.11311349,   9801.38425112],
       ...,
       [  4554.68952884,  11104.82276538,  17949.95400352, ...,
         81955.99898218,  59927.8216453 ,  12464.27150571],
       [  2479.35633719,   7939.49032358,  27262.41824216, ...,
        109916.2858877 ,  55893.63796523,   5658.77226514],
       [  1310.75655817,   3723.6484673 ,  22755.22775115, ...,
         73406.88957754,  35704.1626206 ,   8002.61417131]])

In [8]:
time_steps = 200
feature_length = 18
batch_size = 1

In [9]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.33)

In [10]:
print(len(X_train), len(y_train))
print(len(X_test), len(y_test))

2014 2014
993 993


In [30]:
model = Sequential()
model.add(LSTM(200, input_shape=(time_steps, feature_length)))
model.add(Dense(1, activation="sigmoid"))

In [31]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [13]:
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [32]:
model.fit(X_train, y_train, epochs=10, batch_size=batch_size)

Epoch 1/10
2014/2014 [==============================] - 117s 57ms/step - loss: 0.4956 - accuracy: 0.8272
Epoch 2/10
2014/2014 [==============================] - 111s 55ms/step - loss: 0.4859 - accuracy: 0.8292
Epoch 3/10
2014/2014 [==============================] - 125s 62ms/step - loss: 0.4830 - accuracy: 0.8292
Epoch 4/10
2014/2014 [==============================] - 153s 76ms/step - loss: 0.4813 - accuracy: 0.8282
Epoch 5/10
2014/2014 [==============================] - 244s 121ms/step - loss: 0.4822 - accuracy: 0.8287
Epoch 6/10
2014/2014 [==============================] - 241s 120ms/step - loss: 0.4806 - accuracy: 0.8257
Epoch 7/10
2014/2014 [==============================] - 223s 111ms/step - loss: 0.4873 - accuracy: 0.8173
Epoch 8/10
 237/2014 [==>...........................] - ETA: 3:22 - loss: 0.4632 - accuracy: 0.8439

KeyboardInterrupt: 

In [ ]:
y_train

In [23]:
score = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=0)
print('Test loss:', score[0])
print('Accuracy:', score[1])

Test loss: 0.16622242331504822
Accuracy: 0.8046324253082275


In [26]:
X = np.array(X)
y = np.array(y)
y

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
score_full = model.evaluate(X, y, batch_size=batch_size, verbose=0)
print('Test loss:', score_full[0])
print('Accuracy:', score_full[1])

Test loss: 0.16234374046325684
Accuracy: 0.816095769405365


In [29]:
model.predict(X_test)

32/32 [==============================] - 5s 135ms/step


array([[-1.18858278e-01],
       [ 7.87899494e-02],
       [ 2.98061222e-01],
       [ 4.13207352e-01],
       [ 4.29316312e-01],
       [-6.81213140e-02],
       [ 6.34212494e-02],
       [ 2.03213215e-01],
       [ 1.17686093e-01],
       [ 1.89757049e-01],
       [-2.18964756e-01],
       [ 2.16081709e-01],
       [ 4.74363029e-01],
       [ 4.94412184e-01],
       [ 9.24351811e-02],
       [ 6.76387548e-03],
       [-6.97910190e-02],
       [ 4.27457929e-01],
       [ 4.62375283e-02],
       [ 2.69982129e-01],
       [-1.25474989e-01],
       [ 3.00349265e-01],
       [ 2.72217870e-01],
       [ 2.48137325e-01],
       [ 3.07275772e-01],
       [ 1.48899406e-01],
       [-1.83241963e-02],
       [-3.35246325e-03],
       [ 2.57337660e-01],
       [-3.21242213e-02],
       [ 1.11709833e-02],
       [ 2.05352038e-01],
       [ 3.72302711e-01],
       [-2.02214897e-01],
       [-1.43848360e-01],
       [ 2.75083214e-01],
       [ 1.96925014e-01],
       [ 7.00555444e-02],
       [-1.1